name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        R: [ '3.6.3', '4.0.4' ]

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript R/Profound-Main.R
