name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        R: [ '3.6.3', '4.0.4' ]

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('install.r') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('install.r') }}
      - name: Check initial pop doesn't exist
        run: |
          [ ! -f Inputs/init_pop.rds ]
      - name: Install dependencies
        run: Rscript install.r
      - name: Run PROFOUND without inital pop
        run: Rscript R/Profound-Main.R -p Inputs/init_pop.rds
      - name: Check initial pop exists
        run: |
          [ -f Inputs/init_pop.rds ]
      - name: Run PROFOUND with input pop
        run: Rscript R/Profound-Main.R -p Inputs/init_pop.rds
      - name: Check results exists
        run: |
          [ -f OverdoseDeath.csv ]
